FROM debian:jessie-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        curl \
        dnsutils \
        iptables \
        jq \
        nghttp2 \
        sqlite3 \
        libsqlite3-dev \
    && rm -rf /var/lib/apt/lists/*
